version: '2'

services:
  db:
    image: mysql:5.7.13
    ports:
      - "3306:3306"
    volumes:
      - msr_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KimKyudong1!
      MYSQL_DATABASE: MSR_DB
      MYSQL_USER: msrdb
      MYSQL_PASSWORD: KimKyudong1!

  msr-api:
    depends_on:
      - db    
    image: msr-api:1.0.0
    ports:
      - "8080:8080"
    restart: always

volumes:
  msr_db: